
services:
  # 🕷️ Le Crawler (TitanPro)
  crawler:
    build: .
    container_name: titan_spider
    restart: always
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis:6379
      - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - ./data/output:/app/data/output   # Stockage local des résultats
      - .:/app                           # Montage du code pour dev en temps réel
    shm_size: '2gb'                       # Important pour Playwright
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ⚡ Redis – moteur de queue
  redis:
    image: redis:7-alpine
    container_name: titan_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  # 🍃 MongoDB – stockage des données
  mongodb:
    image: mongo:latest
    container_name: titan_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 📊 Redis Insight – interface optionnelle pour monitorer la queue
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    restart: always

# 📦 Volumes persistants
volumes:
  mongo_data:
  redis_data: